/* js/toc-data.js — generated by tools/generate-book.mjs. Do not edit by hand. */
window.TOC_STRANDS = [
  {
    "strand": "Number",
    "color": "#3B4CA8",
    "topics": [
      {
        "id": "place-value",
        "name": "Place Value & Whole Numbers",
        "year": "Year 6",
        "idea": "Every digit has a value that depends on its position. Moving one place left multiplies its value by 10 — the single rule our whole number system is built on."
      },
      {
        "id": "operations",
        "name": "Operations & Order (BEDMAS)",
        "year": "Year 6",
        "idea": "When a calculation mixes +, −, ×, ÷ and brackets, everyone needs the same answer. BEDMAS fixes the order: Brackets, Exponents, Division/Multiplication (left→right), Addition/Subtraction (left→right)."
      },
      {
        "id": "factors",
        "name": "Factors, Multiples & Primes",
        "year": "Year 6",
        "idea": "Factors divide in exactly; multiples appear in the times-table; a prime has exactly two factors. These ideas power fraction simplifying, HCF and LCM."
      },
      {
        "id": "fractions",
        "name": "Fractions",
        "year": "Year 6",
        "idea": "A fraction like 34 means '3 of 4 equal parts'. Multiplying or dividing top and bottom by the same number gives an equal fraction — how we simplify, compare, add and subtract."
      },
      {
        "id": "decimals",
        "name": "Decimals",
        "year": "Year 6",
        "idea": "Decimals extend place value past the ones into tenths, hundredths and thousandths. They're just fractions with denominators 10, 100, 1000 in compact form."
      },
      {
        "id": "percentages",
        "name": "Percentages",
        "year": "Year 6",
        "idea": "'Per cent' means 'out of 100'. A percentage is a fraction with denominator 100, so 25% = 25/100 = 1/4 — linking straight to fractions and decimals."
      },
      {
        "id": "ratios",
        "name": "Ratios & Rates",
        "year": "Year 7",
        "idea": "A ratio compares quantities of the same kind (2:3); a rate compares different kinds ($/kg, km/h). Both are proportional thinking — scaling while keeping the relationship fixed."
      },
      {
        "id": "integers",
        "name": "Integers (negatives)",
        "year": "Year 7",
        "idea": "Integers include negatives: …−3, −2, −1, 0, 1, 2, 3… They measure things below a reference point — temperatures, debts, depths — with clear rules for +, −, ×."
      },
      {
        "id": "powers",
        "name": "Powers, Roots & Scientific Notation",
        "year": "Year 7",
        "idea": "An index is repeated multiplication: 2³ = 2×2×2. A square root undoes squaring. Scientific notation writes very large/small numbers as a value between 1 and 10 times a power of 10."
      }
    ]
  },
  {
    "strand": "Algebra",
    "color": "#7A3FB0",
    "topics": [
      {
        "id": "patterns",
        "name": "Patterns & Sequences",
        "year": "Year 7",
        "idea": "A sequence is an ordered list following a rule. Spotting the rule predicts any term without listing them all — the doorway to algebra."
      },
      {
        "id": "expressions",
        "name": "Algebraic Expressions",
        "year": "Year 7",
        "idea": "A letter stands for an unknown or changing number. We collect like terms, expand brackets and substitute values — the grammar of algebra."
      },
      {
        "id": "equations",
        "name": "Linear Equations",
        "year": "Year 7",
        "idea": "An equation says two expressions are equal. Solving finds the unknown that keeps the balance true — by doing the same to both sides."
      },
      {
        "id": "inequalities",
        "name": "Inequalities",
        "year": "Year 8",
        "idea": "An inequality (>, <, ≥, ≤) describes a range of values, not a single one. Solving is almost identical to equations — with one crucial twist."
      },
      {
        "id": "graphs",
        "name": "Coordinates & Linear Graphs",
        "year": "Year 8",
        "idea": "The Cartesian plane locates points with (x, y). A straight-line graph like y = 2x + 1 shows every point that makes the equation true."
      }
    ]
  },
  {
    "strand": "Geometry",
    "color": "#1E8A8A",
    "topics": [
      {
        "id": "angles",
        "name": "Angles & Angle Relationships",
        "year": "Year 7",
        "idea": "Angles measure turn. A few facts unlock most problems: on a straight line they add to 180°, around a point to 360°, and in a triangle to 180°."
      },
      {
        "id": "shapes",
        "name": "Triangles, Quadrilaterals & Polygons",
        "year": "Year 7",
        "idea": "Shapes are classified by sides and angles. The angle-sum rules let you find missing angles in any polygon."
      },
      {
        "id": "transformations",
        "name": "Transformations",
        "year": "Year 7",
        "idea": "A transformation moves or resizes a shape: translation (slide), reflection (flip), rotation (turn), enlargement (scale). Coordinates change predictably."
      },
      {
        "id": "pythagoras",
        "name": "Pythagoras' Theorem",
        "year": "Year 8",
        "idea": "In a right-angled triangle, the square of the hypotenuse equals the sum of the squares of the other two sides: a² + b² = c²."
      },
      {
        "id": "circles",
        "name": "Circles",
        "year": "Year 8",
        "idea": "Every circle links its radius to two measures: circumference C = πd (distance around) and area A = πr² (space inside). π ≈ 3.14 is the same ratio for every circle."
      }
    ]
  },
  {
    "strand": "Measurement",
    "color": "#C9791A",
    "topics": [
      {
        "id": "perimeter-area",
        "name": "Perimeter & Area",
        "year": "Year 6",
        "idea": "Perimeter is the distance around a shape (add the sides). Area is the space inside (in squares). Compound shapes split into rectangles and triangles."
      },
      {
        "id": "volume",
        "name": "Volume & Surface Area",
        "year": "Year 8",
        "idea": "Volume is the space inside a 3-D solid (cubic units). Surface area is the total area of all faces. For a cuboid, volume = length × width × height."
      },
      {
        "id": "conversions",
        "name": "Units, Conversions & Rates",
        "year": "Year 7",
        "idea": "Metric units scale by powers of 10 (1 km = 1000 m). Compound measures like speed combine two quantities (distance ÷ time), and one triangle relationship finds any of the three."
      }
    ]
  },
  {
    "strand": "Statistics & Probability",
    "color": "#B5405C",
    "topics": [
      {
        "id": "statistics",
        "name": "Data & Averages",
        "year": "Year 7",
        "idea": "Statistics summarise data. The mean (add ÷ count), median (middle in order) and mode (most common) describe the centre; the range (max − min) describes spread."
      },
      {
        "id": "probability",
        "name": "Probability",
        "year": "Year 8",
        "idea": "Probability measures how likely an event is, from 0 (impossible) to 1 (certain). For equally likely outcomes it's favourable ÷ total."
      }
    ]
  }
];
